### ISSUE TITLE
WSL installation not compiling with CUDA support

### ISSUE THREAD

**Issue by aadharna** [shacklettbp/gpu_hideseek#3]
So, I got the install to run in WSL and I can run (with some editing) the cpu_benchmark.py file. 

But, when I try to run the `benchmark.py` file for the GPU benchmark I get the following error: 

```
Error at /home/roque/mapo/hs/gpu_hideseek/src/mgr.cpp:289 in static Manager::Impl *GPUHideSeek::Manager::Impl::init(const GPUHideSeek::Manager::Config &, const viz::VizECSBridge *, const render::BatchRendererECSBridge *)
Madrona was not compiled with CUDA support
```

I followed the instructions in the README and the distro has access to my GPU. Is there a different flag I need to pass in the cmaking perhaps? Running nvidia-smi in my linux terminal brings up my GPU just fine so if there was an automatic check to determine cuda vs non-cuda compilation, I would think that would have passed.

**Comment by shacklettbp** [comment]
I'm not sure why CUDA isn't found for you, I've had CUDA successfully picked up in WSL. Most likely your CUDA version is too old or cmake isn't finding it (non-standard install location). You could read the cmake verbose logs in the build directory to try and debug.

Unfortunately, it's all a moot point.

The GPU backend doesn't work under WSL. CUDA under WSL inherits the limitations that the windows driver model imposes on CUDA's unified memory support, unfortunately, which currently means Madrona's GPU backend cannot run.

Fixing this requires changes to memory allocation in the GPU backend that are certainly possible but not a priority for me right now. If those changes are made, Madrona's GPU backend would support Windows and WSL wouldn't be required.

**Comment by aadharna** [comment]
Okay. So, what that tells me is that I should use the CPU version that's working for coding purposes and then just run my experiments for real on a Linux machine. 

You don't happen to have a docker container setup, do you? 

Btw, this is really cool work -- thank you for building out the engine! I'd been toying with recreating the H&S domain from the OAI mujoco code in the new mujoco sim and it was a nightmare. 

----  

I saw that you had written up a MAPPO implementation for the escape room, should that implementation function with H&S plugged in instead?

**Comment by shacklettbp** [comment]
Yeah. I do a lot of dev on mac and windows but the real training runs basically need to be on linux for now. PyTorch is also a lot faster on linux than windows (even both CUDA enabled), in my experience.

I don't have a docker setup unfortunately. I'm happy to guide you through the packages to install if you run into problems and if you want to contribute a Dockerfile that could be cool (I don't use Docker).

Yeah the core MAPPO implementation in madrona_escape_room will work. Obviously you'd need to pass in different tensors, and you'd want a more complex policy probably. One problem is that if you're trying to use the H&S paper's hyperparameters, the MAPPO implementation in madrona_escape_room will out-of-memory because it tries to store the long rollouts completely in GPU memory.

madrona_escape_room's PPO implementation is actually just a copy / rename of the madrona-learn repo: https://github.com/shacklettbp/madrona-learn. The train_exps branch on *this* repo is a very initial attempt to hook up this environment to the madrona-learn PPO implementation. It doesn't have the full policy implemented for example.

It could be a useful starting point if you're interested in getting started with this repo though.

**Comment by aadharna** [comment]
> One problem is that if you're trying to use the H&S paper's hyperparameters, the MAPPO implementation in madrona_escape_room will out-of-memory because it tries to store the long rollouts completely in GPU memory.

That is good to know! 

I'm definitely gonna take some time this weekend to dive into the MAPPO implementation. While I've written my own before, when doing multi-agent work, I usually try to offload the learning algos to tools like rllib and I highly doubt that it could be an easy plug-and-play combination using madrona with rllib. 

Thanks for the pointer to the `train_exps` branch! 

For now, I think we should close this since the issue is solved, but I would love to chat about what you all have done and how I could either contribute something or get some advice on how would be a good way to adapt it to my problems.

**Comment by aadharna** [comment]
Also, any dependencies / installation instructions on the madrona-learn repo I should be aware of beyond the usual (torch)?

**Comment by shacklettbp** [comment]
No I don't think so, should just be pytorch + pip install -e.

Feel free to email me at my Stanford email (can find it on my website), I'd be happy to set up time for a short chat.
